# Generated by Django 4.1.2 on 2022-10-15 11:02

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('ID', models.IntegerField(default=0, help_text='Person ID', primary_key=True, serialize=False, unique=True)),
                ('forename', models.CharField(help_text='Forename / given name', max_length=20)),
                ('surname', models.CharField(help_text='Surname', max_length=30)),
                ('parent_id', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, help_text='Parent ID list', null=True, size=None)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['ID', 'surname', 'forename', 'parent_id'],
            },
        ),
    ]
